# Generated by Django 3.2 on 2022-09-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='user',
            field=models.CharField(default='anonymous', max_length=40),
        ),
    ]
